import { useGLTF } from '@react-three/drei';

export function Model(props) {
	const { nodes, materials } = useGLTF('/Reaponsive.glb');
	return (
		<group
			{...props}
			dispose={null}>
			<mesh
				geometry={nodes.Object_6.geometry}
				material={materials['Logo.001']}
			/>
			<mesh
				geometry={nodes.Object_9.geometry}
				material={materials['Bezel.001']}
			/>
			<mesh
				geometry={nodes.Object_11.geometry}
				material={materials['Body.001']}
			/>
			<mesh
				geometry={nodes.Object_13.geometry}
				material={materials['Camera_Glass.001']}
			/>
			<mesh
				geometry={nodes.Object_15.geometry}
				material={materials['Lens.001']}
			/>
			<mesh
				geometry={nodes.Object_17.geometry}
				material={materials['Material.013']}
			/>
			<mesh
				geometry={nodes.Object_19.geometry}
				material={materials['material.001']}
			/>
			<mesh
				geometry={nodes.Object_21.geometry}
				material={materials['Wallpaper.001']}
			/>
			<mesh
				geometry={nodes.Object_24.geometry}
				material={materials['Screen_Glass.001']}
			/>
			<mesh
				geometry={nodes.Object_27.geometry}
				material={materials['Frame.001']}
			/>
			<mesh
				geometry={nodes.Object_30.geometry}
				material={materials['Body.001']}
			/>
			<mesh
				geometry={nodes.Object_32.geometry}
				material={materials['Camera_Frame.002']}
			/>
			<mesh
				geometry={nodes.Object_34.geometry}
				material={materials['Glass.001']}
			/>
			<mesh
				geometry={nodes.Object_36.geometry}
				material={materials['material.001']}
			/>
			<mesh
				geometry={nodes.Object_39.geometry}
				material={materials['Black_Glass.001']}
			/>
			<mesh
				geometry={nodes.Object_41.geometry}
				material={materials['Body.001']}
			/>
			<mesh
				geometry={nodes.Object_43.geometry}
				material={materials['Camera_Frame.003']}
			/>
			<mesh
				geometry={nodes.Object_45.geometry}
				material={materials['Camera_Glass.001']}
			/>
			<mesh
				geometry={nodes.Object_47.geometry}
				material={materials['Flash.001']}
			/>
			<mesh
				geometry={nodes.Object_49.geometry}
				material={materials['Gray_Glass.001']}
			/>
			<mesh
				geometry={nodes.Object_51.geometry}
				material={materials['Lens.001']}
			/>
			<mesh
				geometry={nodes.Object_53.geometry}
				material={materials['Port.001']}
			/>
			<mesh
				geometry={nodes.Object_56.geometry}
				material={materials['Material.015']}
			/>
			<mesh
				geometry={nodes.Object_59.geometry}
				material={materials['Frame.001']}
			/>
			<mesh
				geometry={nodes.Object_61.geometry}
				material={materials['Antenna.001']}
			/>
			<mesh
				geometry={nodes.Object_63.geometry}
				material={materials['Frame2.001']}
			/>
			<mesh
				geometry={nodes.Object_65.geometry}
				material={materials['Frame.001']}
			/>
			<mesh
				geometry={nodes.Object_67.geometry}
				material={materials['material.001']}
			/>
			<mesh
				geometry={nodes.Object_69.geometry}
				material={materials['Port.001']}
			/>
		</group>
	);
}

useGLTF.preload('/Reaponsive.glb');
